USE dbLibrary
GO

CREATE TABLE PUBLISHER
(
	Name NVARCHAR(50) PRIMARY KEY,
	[Address] NVARCHAR(120) NULL,
	Phone NVARCHAR(25) NULL
);

CREATE TABLE BOOK
(
	BookId INT PRIMARY KEY,
	Title NVARCHAR(50) NOT NULL,
	PublisherName NVARCHAR(50) NOT NULL
);

--ADD FOREIGN KEY CONSTRAINT THAT I FORGOT
ALTER TABLE BOOK
ADD FOREIGN KEY (PublisherName) REFERENCES PUBLISHER(Name)
;

--ALLOW Title COLUMN TO ACCEPT MORE CHARACTERS
ALTER TABLE BOOK
ALTER COLUMN Title NVARCHAR(100)
;

CREATE TABLE BOOK_AUTHORS
(
	BookId INT FOREIGN KEY REFERENCES BOOK(BookId),
	AuthorName NVARCHAR(50) NOT NULL
);

CREATE TABLE LIBRARY_BRANCH
(
	BranchId INT PRIMARY KEY,
	BranchName NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(120) NULL
);

CREATE TABLE BOOK_COPIES
(
	BookId INT FOREIGN KEY REFERENCES BOOK(BookId),
	BranchId INT FOREIGN KEY REFERENCES LIBRARY_BRANCH(BranchId),
	No_Of_Copies INT NOT NULL
);

CREATE TABLE BORROWER
(
	CardNo INT PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(120) NOT NULL,
	Phone NVARCHAR(25) NOT NULL
);

CREATE TABLE BOOK_LOANS
(
	BookId INT FOREIGN KEY REFERENCES BOOK(BookId),
	BranchId  INT FOREIGN KEY REFERENCES LIBRARY_BRANCH(BranchId),
	CardNo INT FOREIGN KEY REFERENCES BORROWER(CardNo),
	DateOut Date NOT NULL,
	DueDate Date NOT NULL
);
